/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GroupSelectionPanel.java
 *
 * Created on Dec 20, 2011, 11:01:49 PM
 */
package de.tor.tribes.ui;

import java.awt.GridBagConstraints;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.JComboBox;
import javax.swing.JFrame;

/**
 *
 * @author Torridity
 */
public class GroupSelectionPanel extends javax.swing.JPanel {

    private int rowCount = 0;
    private JComboBox[][] boxes = new JComboBox[2][10];

    /** Creates new form GroupSelectionPanel */
    public GroupSelectionPanel() {
        initComponents();
        addRow();
    }

    private void addRow() {
        if (rowCount == 10) {
            return;
        }
        GridBagConstraints gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = rowCount;
        JComboBox groupBox = getGroupBox();
        add(groupBox, gridBagConstraints);
        JComboBox relationBox = null;
        if (rowCount != 0) {
            gridBagConstraints.gridx = 1;
            gridBagConstraints.gridy = rowCount - 1;
            relationBox = getRelationBox();
            add(relationBox, gridBagConstraints);
            gridBagConstraints.gridy = rowCount;
            boxes[1][rowCount - 1] = relationBox;
        }
        remove(jAddButton);
        remove(jRemoveButton);
        gridBagConstraints.gridx = 2;
        add(jAddButton, gridBagConstraints);
        gridBagConstraints.gridx = 3;
        add(jRemoveButton, gridBagConstraints);
        boxes[0][rowCount] = groupBox;
        rowCount++;
        updateUI();
    }

    private void removeRow() {
        if (rowCount > 1) {
            remove(boxes[0][rowCount - 1]);
            remove(boxes[1][rowCount - 2]);
            rowCount--;
            remove(jAddButton);
            remove(jRemoveButton);
            GridBagConstraints gridBagConstraints = new GridBagConstraints();
            gridBagConstraints.gridx = 2;
            gridBagConstraints.gridy = rowCount - 1;
            add(jAddButton, gridBagConstraints);
            gridBagConstraints.gridx = 3;
            add(jRemoveButton, gridBagConstraints);
            updateUI();
        }
    }

    private JComboBox getRelationBox() {
        return new JComboBox(new Object[]{"UND", "ODER", "NICHT"});
    }

    private JComboBox getGroupBox() {
        return new JComboBox(new Object[]{"Off", "Def", "Aufbau", "AG"});
    }

    public String getEquation() {
        String result = "";
        for (int i = 0; i < boxes[0].length; i++) {
            JComboBox groupBox = boxes[0][i];
            JComboBox relationBox = boxes[1][i];
            if (groupBox != null) {
                result += groupBox.getSelectedItem();
            }
            if (relationBox != null) {
                result += relationBox.getSelectedItem();
            }
        }

        return result;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAddButton = new javax.swing.JButton();
        jRemoveButton = new javax.swing.JButton();

        jAddButton.setText("+");
        jAddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fireAddRowEvent(evt);
            }
        });

        jRemoveButton.setText("-");
        jRemoveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fireRemoveRowEvent(evt);
            }
        });

        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents

    private void fireAddRowEvent(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fireAddRowEvent
        addRow();
    }//GEN-LAST:event_fireAddRowEvent

    private void fireRemoveRowEvent(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fireRemoveRowEvent
        removeRow();
    }//GEN-LAST:event_fireRemoveRowEvent
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddButton;
    private javax.swing.JButton jRemoveButton;
    // End of variables declaration//GEN-END:variables

    public static void main(String[] args) {
        JFrame f = new JFrame();
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        final GroupSelectionPanel panel = new GroupSelectionPanel();
        f.getContentPane().add(panel);
        f.pack();
        f.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                System.out.println(panel.getEquation());
            }
        });
        f.setVisible(true);

    }
}
