/*
 * TestFrame.java
 *
 * Created on 18. Juni 2008, 19:12
 */
package de.tor.tribes.ui;

import com.visutools.nav.bislider.BiSlider;
import de.tor.tribes.ui.components.MThumbSlider;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.DecimalFormat;
import javax.swing.BoundedRangeModel;

/**
 *
 * @author  Charon
 */
public class TestFrame extends javax.swing.JFrame {

    public enum Command {

        MDSLIST,
        TEST
    };

    /** Creates new form TestFrame */
    public TestFrame() {
        initComponents();
        biSlider1.setMinimumValue(0);
        biSlider1.setMaximumValue(24);
        biSlider1.setSegmentSize(1);
        biSlider1.setUnit("h");
    //bs.set
        /*System.getProperties().put("proxySet", "true");
    System.getProperties().put("proxyHost", "proxy.fzk.de");
    System.getProperties().put("proxyPort", "8000");
    jEditorPane1.setContentType("text/html");
    try {
    URL url = new URL("http://www.heise.de");

    jEditorPane1.setPage(url);
    } catch (Exception e) {
    e.printStackTrace();
    }*/
    /* frameControlPanel1.setupPanel(this, true, true);
    frameControlPanel1.setTitle("Test Frame with title and laberzeug und so weiet damit es lang");*/
    //  setLocation(200, 500);

    /*new Thread(new Runnable() {
    
    public void run() {
    int heigth = 10;
    boolean inv = false;
    int y = getLocation().y ;
    while (true) {
    try {
    setSize(getWidth(), heigth);
    setLocation(getLocation().x, y - heigth);
    Thread.sleep(50);
    
    heigth += (inv) ? -10 : 10;
    if (heigth >= 75) {
    Thread.sleep(5000);
    inv = true;
    } else if (heigth <= 0) {
    dispose();
    return;
    }
    
    } catch (Exception e) {
    }
    }
    }
    }).start();*/
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        biSlider1 = new com.visutools.nav.bislider.BiSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().add(biSlider1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) throws Exception {

    try {
    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
    } catch (Exception e) {
    }
    java.awt.EventQueue.invokeLater(new Runnable() {

    public void run() {
    new TestFrame().setVisible(true);
    }
    });

    }*/
    public static void main(String args[]) {
        /*try {
        UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
        } catch (Exception ex) {
        System.err.println("Error loading L&F: " + ex);
        }*/

       /* TestFrame f = new TestFrame();
        f.addWindowListener(new WindowAdapter() {

            public void windowClosing(WindowEvent e) {
                System.exit(0);
            }
        });
        f.setSize(300, 100);
        f.setVisible(true);*/
        new com.visutools.nav.bislider.Test().setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.visutools.nav.bislider.BiSlider biSlider1;
    // End of variables declaration//GEN-END:variables
}
