/* 
 * Copyright 2015 Torridity.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.tor.tribes.ui.panels;

/**
 *
 * @author Torridity
 */
public class TAPAttackInfoPanel extends javax.swing.JPanel {

    private static TAPAttackInfoPanel SINGLETON = null;

    public static synchronized TAPAttackInfoPanel getSingleton() {
        if (SINGLETON == null) {
            SINGLETON = new TAPAttackInfoPanel();
        }
        return SINGLETON;
    }

    /**
     * Creates new form TAPAttackInfoPanel
     */
    TAPAttackInfoPanel() {
        initComponents();
    }

    /*
     * public void setAttacks(int pAttacks) { jAttacks.setText(Integer.toString(pAttacks)); }
     *
     * public void setAttackFakes(int pAttackFakes) { jAttackFakes.setText(Integer.toString(pAttackFakes)); }
     *
     * public void setTarget(int pTargets) { jTargets.setText(Integer.toString(pTargets)); }
     *
     * public void setTargetFakes(int pTargetFakes) { jTargetFakes.setText(Integer.toString(pTargetFakes));
    }
     */
    public void updateSource(int pAttacks, int pAttackFakes, int pIgnoredAttacks) {
        jAttacks.setText(Integer.toString(pAttacks));
        jAttackFakes.setText(Integer.toString(pAttackFakes));
        jIgnoredAttacks.setText(Integer.toString(pIgnoredAttacks));
    }

    public void updateTarget(int pTargets, int pTargetFakes, int pTargetIgnored) {
        jTargets.setText(Integer.toString(pTargets));
        jTargetFakes.setText(Integer.toString(pTargetFakes));
        jTargetIgnored.setText(Integer.toString(pTargetIgnored));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jAttacks = new javax.swing.JLabel();
        jTargets = new javax.swing.JLabel();
        jAttackFakes = new javax.swing.JLabel();
        jIgnoredAttacks = new javax.swing.JLabel();
        jTargetFakes = new javax.swing.JLabel();
        jTargetIgnored = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Informationen", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        setMinimumSize(new java.awt.Dimension(200, 90));
        setPreferredSize(new java.awt.Dimension(200, 90));
        setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/axe.png"))); // NOI18N
        jLabel1.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jLabel1, gridBagConstraints);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/attack.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jLabel3, gridBagConstraints);

        jAttacks.setBackground(new java.awt.Color(0, 153, 0));
        jAttacks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jAttacks.setText("0");
        jAttacks.setToolTipText("Angegebene Herkunftsdörfer für Angriffe");
        jAttacks.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jAttacks, gridBagConstraints);

        jTargets.setBackground(new java.awt.Color(0, 153, 0));
        jTargets.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTargets.setText("0");
        jTargets.setToolTipText("Angegebene Zieldörfer für Angriffe");
        jTargets.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jTargets, gridBagConstraints);

        jAttackFakes.setBackground(new java.awt.Color(255, 255, 0));
        jAttackFakes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jAttackFakes.setText("0");
        jAttackFakes.setToolTipText("Angegebene Herkunftsdörfer für Fakes");
        jAttackFakes.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jAttackFakes, gridBagConstraints);

        jIgnoredAttacks.setBackground(new java.awt.Color(255, 0, 0));
        jIgnoredAttacks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jIgnoredAttacks.setText("0");
        jIgnoredAttacks.setToolTipText("Ignorierte Herkunftsdörfer");
        jIgnoredAttacks.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jIgnoredAttacks, gridBagConstraints);

        jTargetFakes.setBackground(new java.awt.Color(255, 255, 0));
        jTargetFakes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTargetFakes.setText("0");
        jTargetFakes.setToolTipText("Angegebene Zieldörfer für Fakes");
        jTargetFakes.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jTargetFakes, gridBagConstraints);

        jTargetIgnored.setBackground(new java.awt.Color(255, 0, 0));
        jTargetIgnored.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTargetIgnored.setText("0");
        jTargetIgnored.setToolTipText("Ignorierte Zieldörfer");
        jTargetIgnored.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jTargetIgnored, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAttackFakes;
    private javax.swing.JLabel jAttacks;
    private javax.swing.JLabel jIgnoredAttacks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jTargetFakes;
    private javax.swing.JLabel jTargetIgnored;
    private javax.swing.JLabel jTargets;
    // End of variables declaration//GEN-END:variables
}
