/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MultiBooleanTableCellEditor.java
 *
 * Created on Jan 25, 2011, 6:47:50 PM
 */
package de.tor.tribes.ui.editors;

import javax.swing.JFrame;

/**
 *
 * @author Torridity
 */
public class MultiBooleanTableCellEditor extends javax.swing.JPanel {

    public static final int VALUE1 = 8;
    public static final int VALUE2 = 4;
    public static final int VALUE3 = 2;
    public static final int VALUE4 = 1;

    /** Creates new form MultiBooleanTableCellEditor */
    public MultiBooleanTableCellEditor() {
        initComponents();
    }

    public static boolean isOptionSet(int pValue, int pOption) {
        switch (pOption) {
            case VALUE1:
            case VALUE2:
            case VALUE3:
            case VALUE4:
                return ((pValue & pOption) != 0);
            default:
                return false;
        }
    }

    public int getSelection() {
        int value = 0;
        if (jValue1.isSelected()) {
            value |= VALUE1;
        }
        if (jValue2.isSelected()) {
            value |= VALUE2;
        }
        if (jValue3.isSelected()) {
            value |= VALUE3;
        }
        if (jValue4.isSelected()) {
            value |= VALUE4;
        }
        return value;
    }

    public void setSelection(int pSelection) {
        jValue1.setSelected((pSelection & VALUE1) != 0);
        jValue2.setSelected((pSelection & VALUE2) != 0);
        jValue3.setSelected((pSelection & VALUE3) != 0);
        jValue4.setSelected((pSelection & VALUE4) != 0);
    }

    public static void main(String[] args) {
        int value = 0;
        value |= VALUE2;
        value |= VALUE4;

        JFrame f = new JFrame();
        MultiBooleanTableCellEditor ed = new MultiBooleanTableCellEditor();
        ed.setSelection(value);
        f.add(ed);
        f.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jValue2 = new javax.swing.JCheckBox();
        jValue3 = new javax.swing.JCheckBox();
        jValue1 = new javax.swing.JCheckBox();
        jValue4 = new javax.swing.JCheckBox();

        jValue2.setBackground(new java.awt.Color(0, 255, 0));
        jValue2.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jValue2.setMaximumSize(new java.awt.Dimension(18, 18));
        jValue2.setMinimumSize(new java.awt.Dimension(18, 18));
        jValue2.setPreferredSize(new java.awt.Dimension(18, 18));

        jValue3.setBackground(new java.awt.Color(0, 0, 255));
        jValue3.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jValue3.setMaximumSize(new java.awt.Dimension(18, 18));
        jValue3.setMinimumSize(new java.awt.Dimension(18, 18));
        jValue3.setPreferredSize(new java.awt.Dimension(18, 18));

        jValue1.setBackground(new java.awt.Color(255, 0, 0));
        jValue1.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jValue1.setMaximumSize(new java.awt.Dimension(18, 18));
        jValue1.setMinimumSize(new java.awt.Dimension(18, 18));
        jValue1.setPreferredSize(new java.awt.Dimension(18, 18));

        jValue4.setBackground(new java.awt.Color(255, 0, 255));
        jValue4.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jValue4.setMaximumSize(new java.awt.Dimension(18, 18));
        jValue4.setMinimumSize(new java.awt.Dimension(18, 18));
        jValue4.setPreferredSize(new java.awt.Dimension(18, 18));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jValue1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jValue2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jValue3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jValue4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jValue1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jValue2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jValue3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jValue4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jValue1;
    private javax.swing.JCheckBox jValue2;
    private javax.swing.JCheckBox jValue3;
    private javax.swing.JCheckBox jValue4;
    // End of variables declaration//GEN-END:variables
}
