/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WelcomePanel.java
 *
 * Created on Jan 2, 2012, 1:43:21 PM
 */
package de.tor.tribes.ui.wiz.red;

import de.tor.tribes.util.JOptionPaneHelper;
import java.util.Map;
import javax.swing.ImageIcon;
import org.netbeans.spi.wizard.Wizard;
import org.netbeans.spi.wizard.WizardPage;
import org.netbeans.spi.wizard.WizardPanelNavResult;

/**
 *
 * @author Torridity
 */
public class ResourceDistributorWelcomePanel extends WizardPage {

    private static ResourceDistributorWelcomePanel singleton = null;
    public static final String TYPE = "type";
    public final static Integer BALANCE_DISTRIBUTION = 0;
    public final static Integer FILL_DISTRIBUTION = 1;
    public final static Integer LOAD_DISTRIBUTION = 2;

    public static synchronized ResourceDistributorWelcomePanel getSingleton() {
        if (singleton == null) {
            singleton = new ResourceDistributorWelcomePanel();
        }
        return singleton;
    }

    /**
     * Creates new form WelcomePanel
     */
    ResourceDistributorWelcomePanel() {
        initComponents();
        jEqualButton.setIcon(new ImageIcon("./graphics/big/distribute_equal.png"));
        jFillButton.setIcon(new ImageIcon("./graphics/big/fill_distribution.png"));
        jLoadButton.setIcon(new ImageIcon("./graphics/big/load_transports.png"));
    }

    public static String getDescription() {
        return "Willkommen";
    }

    public static String getStep() {
        return "id-welcome";
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jEqualButton = new javax.swing.JToggleButton();
        jFillButton = new javax.swing.JToggleButton();
        jLoadButton = new javax.swing.JToggleButton();

        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(600, 500));
        setLayout(new java.awt.BorderLayout());

        jTextPane1.setContentType("text/html");
        jTextPane1.setEditable(false);
        jTextPane1.setText("<html><b>Willkommen beim DS Workbench Rohstoffverteiler.</b><br/><br/>\n\n</html>");
        jScrollPane1.setViewportView(jTextPane1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        buttonGroup1.add(jEqualButton);
        jEqualButton.setSelected(true);
        jEqualButton.setMaximumSize(new java.awt.Dimension(80, 80));
        jEqualButton.setMinimumSize(new java.awt.Dimension(80, 80));
        jEqualButton.setPreferredSize(new java.awt.Dimension(80, 80));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jEqualButton, gridBagConstraints);

        buttonGroup1.add(jFillButton);
        jFillButton.setMaximumSize(new java.awt.Dimension(80, 80));
        jFillButton.setMinimumSize(new java.awt.Dimension(80, 80));
        jFillButton.setPreferredSize(new java.awt.Dimension(80, 80));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jFillButton, gridBagConstraints);

        buttonGroup1.add(jLoadButton);
        jLoadButton.setMaximumSize(new java.awt.Dimension(80, 80));
        jLoadButton.setMinimumSize(new java.awt.Dimension(80, 80));
        jLoadButton.setPreferredSize(new java.awt.Dimension(80, 80));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLoadButton, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToggleButton jEqualButton;
    private javax.swing.JToggleButton jFillButton;
    private javax.swing.JToggleButton jLoadButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public WizardPanelNavResult allowNext(String string, Map map, Wizard wizard) {
        if (jLoadButton.isSelected()) {
            if (!ResourceDistributorFinishPanel.getSingleton().loadTransports()) {
                JOptionPaneHelper.showWarningBox(ResourceDistributorWelcomePanel.this, "Keine gespeicherten Transporte gefunden.\nBitte starte eine neue Berechnung.", "Warnung");
                return WizardPanelNavResult.REMAIN_ON_PAGE;
            }
        }

        int type = BALANCE_DISTRIBUTION;
        if (jFillButton.isSelected()) {
            type = FILL_DISTRIBUTION;
        } else if (jLoadButton.isSelected()) {
            type = LOAD_DISTRIBUTION;
        }
        map.put(TYPE, new Integer(type));
        return WizardPanelNavResult.PROCEED;
    }

    @Override
    public WizardPanelNavResult allowBack(String string, Map map, Wizard wizard) {
        return WizardPanelNavResult.PROCEED;

    }

    @Override
    public WizardPanelNavResult allowFinish(String string, Map map, Wizard wizard) {
        return WizardPanelNavResult.PROCEED;
    }
}
