package de.tor.tribes.ui.components;


import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JFrame;
import javax.swing.JLabel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TimePicker.java
 *
 * Created on 18.02.2010, 14:25:29
 */
/**
 *
 * @author Jejkal
 */
public class TimePicker extends javax.swing.JPanel {

    /** Creates new form TimePicker */
    public TimePicker() {
        initComponents();
        addHourLabels();
        addMinuteLabels(false);
    }

    public void addHourLabels() {

        for (int j = 0; j < 24; j++) {
            JLabel jLabel1 = new JLabel();
            jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel1.setText(Integer.toString(j));
            jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
            jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            jLabel1.setMaximumSize(new java.awt.Dimension(30, 20));
            jLabel1.setMinimumSize(new java.awt.Dimension(30, 20));
            jLabel1.setPreferredSize(new java.awt.Dimension(30, 20));
            jLabel1.setOpaque(true);
            jLabel1.setBackground(Color.LIGHT_GRAY);
            jLabel1.addMouseListener(new MouseListener() {

                public void mouseClicked(MouseEvent e) {
                }

                public void mousePressed(MouseEvent e) {
                }

                public void mouseReleased(MouseEvent e) {
                }

                public void mouseEntered(MouseEvent e) {
                    ((JLabel) e.getSource()).setBackground(Color.YELLOW.brighter());
                }

                public void mouseExited(MouseEvent e) {
                    ((JLabel) e.getSource()).setBackground(Color.LIGHT_GRAY);
                }
            });
            jPanel1.add(jLabel1);
        }


    }

    public void addMinuteLabels(boolean pEachMinute) {
        int max = 0;
        if (pEachMinute) {
            jPanel3.setLayout(new java.awt.GridLayout(12, 5));
            jPanel3.setSize(360, 240);
            max = 60;
        } else {
            jPanel3.setLayout(new java.awt.GridLayout(2, 6));
            jPanel3.setSize(360, 40);
            max = 12;
        }


        for (int j = 0; j < max; j++) {
            JLabel jLabel1 = new JLabel();
            jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            int num = j;
            if (!pEachMinute) {
                num = j * 5;
            }
            if (num < 10) {
                jLabel1.setText(":0" + Integer.toString(num));
            } else {
                jLabel1.setText(":" + Integer.toString(num));
            }

            jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder());
            jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            jLabel1.setMaximumSize(new java.awt.Dimension(30, 20));
            jLabel1.setMinimumSize(new java.awt.Dimension(30, 20));
            jLabel1.setPreferredSize(new java.awt.Dimension(30, 20));

            jLabel1.setOpaque(true);
            jLabel1.setBackground(Color.WHITE);
            jPanel3.add(jLabel1);
        }
        jPanel3.setBackground(Color.WHITE);
    }

    public static void main(String[] args) {
        JFrame f = new JFrame();
        f.add(new TimePicker());
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        f.pack();
        f.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        jPanel1.setMaximumSize(new java.awt.Dimension(360, 40));
        jPanel1.setMinimumSize(new java.awt.Dimension(360, 40));
        jPanel1.setPreferredSize(new java.awt.Dimension(360, 40));
        jPanel1.setLayout(new java.awt.GridLayout(2, 12));

        jPanel3.setMaximumSize(new java.awt.Dimension(360, 40));
        jPanel3.setMinimumSize(new java.awt.Dimension(360, 40));
        jPanel3.setPreferredSize(new java.awt.Dimension(360, 40));
        jPanel3.setLayout(new java.awt.GridLayout(2, 6));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(139, 139, 139))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
