/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DSWorkbenchReTimerFrame.java
 *
 * Created on 22.12.2009, 13:43:21
 */
package de.tor.tribes.ui;

import de.tor.tribes.types.Village;
import de.tor.tribes.util.JOptionPaneHelper;
import de.tor.tribes.util.parser.VillageParser;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.StringTokenizer;
import org.apache.log4j.Logger;

/**
 *
 * @author Jejkal
 */
public class DSWorkbenchReTimerFrame extends AbstractDSWorkbenchFrame {

    private static Logger logger = Logger.getLogger("ReTimeTool");
    private static DSWorkbenchReTimerFrame SINGLETON = null;

    public static synchronized DSWorkbenchReTimerFrame getSingleton() {
        if (SINGLETON == null) {
            SINGLETON = new DSWorkbenchReTimerFrame();
        }
        return SINGLETON;
    }

    /** Creates new form DSWorkbenchReTimerFrame */
    DSWorkbenchReTimerFrame() {
        initComponents();
    }


    /*OPERA
    Herkunft	Spieler:	Rattenfutter
    Dorf:	001 Rattennest (486|833) K84
    Ziel	Spieler:	Rattenfutter
    Dorf:	005 Rattennest (486|834) K84
    Ankunft:	22.12.09 13:57:44:321
    Ankunft in:	0:08:34
     *
     *
     *
     * FF
    Herkunft	Spieler:	Rattenfutter
    Dorf:	001 Rattennest (486|833) K84
    Ziel	Spieler:	Rattenfutter
    Dorf:	005 Rattennest (486|834) K84
    Dauer:	0:09:00
    Ankunft:	22.12.09 14:02:30.232
    Ankunft in:	0:08:41
    » abbrechen
     */
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jComandArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSourceVillage = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTargetVillage = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jArriveField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jAxeBox = new javax.swing.JCheckBox();
        jSwordBox = new javax.swing.JCheckBox();
        jSpyBox = new javax.swing.JCheckBox();
        jLightBox = new javax.swing.JCheckBox();
        jHeavyBox = new javax.swing.JCheckBox();
        jRamBox = new javax.swing.JCheckBox();
        jPalaBox = new javax.swing.JCheckBox();
        jSnobBox = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jParserInfo = new javax.swing.JTextPane();
        jCheckBox1 = new javax.swing.JCheckBox();

        jPanel1.setBackground(new java.awt.Color(239, 235, 223));

        jComandArea.setColumns(20);
        jComandArea.setRows(5);
        jComandArea.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                fireComandDataChangedEvent(evt);
            }
        });
        jScrollPane1.setViewportView(jComandArea);

        jLabel1.setText("Angriffsbefehl");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Gelesene Werte"));
        jPanel2.setOpaque(false);

        jLabel2.setText("Herkunft");

        jLabel3.setText("Ziel");

        jLabel4.setText("Ankunft");

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(4, 2));

        jAxeBox.setText("Axt");
        jAxeBox.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/bullet_ball_red.png"))); // NOI18N
        jAxeBox.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/bullet_ball_red.png"))); // NOI18N
        jAxeBox.setDoubleBuffered(true);
        jAxeBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/bullet_ball_grey.png"))); // NOI18N
        jAxeBox.setOpaque(false);
        jAxeBox.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/axe.png"))); // NOI18N
        jAxeBox.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/bullet_ball_green.png"))); // NOI18N
        jPanel3.add(jAxeBox);

        jSwordBox.setText("Schwert");
        jSwordBox.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/bullet_ball_red.png"))); // NOI18N
        jSwordBox.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/bullet_ball_red.png"))); // NOI18N
        jSwordBox.setDoubleBuffered(true);
        jSwordBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/bullet_ball_grey.png"))); // NOI18N
        jSwordBox.setOpaque(false);
        jSwordBox.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/axe.png"))); // NOI18N
        jSwordBox.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/bullet_ball_green.png"))); // NOI18N
        jPanel3.add(jSwordBox);

        jSpyBox.setText("Späher");
        jSpyBox.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/bullet_ball_red.png"))); // NOI18N
        jSpyBox.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/bullet_ball_red.png"))); // NOI18N
        jSpyBox.setDoubleBuffered(true);
        jSpyBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/bullet_ball_grey.png"))); // NOI18N
        jSpyBox.setOpaque(false);
        jSpyBox.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/axe.png"))); // NOI18N
        jSpyBox.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/bullet_ball_green.png"))); // NOI18N
        jPanel3.add(jSpyBox);

        jLightBox.setText("LKav");
        jLightBox.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/bullet_ball_red.png"))); // NOI18N
        jLightBox.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/bullet_ball_red.png"))); // NOI18N
        jLightBox.setDoubleBuffered(true);
        jLightBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/bullet_ball_grey.png"))); // NOI18N
        jLightBox.setOpaque(false);
        jLightBox.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/axe.png"))); // NOI18N
        jLightBox.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/bullet_ball_green.png"))); // NOI18N
        jPanel3.add(jLightBox);

        jHeavyBox.setText("SKav");
        jHeavyBox.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/bullet_ball_red.png"))); // NOI18N
        jHeavyBox.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/bullet_ball_red.png"))); // NOI18N
        jHeavyBox.setDoubleBuffered(true);
        jHeavyBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/bullet_ball_grey.png"))); // NOI18N
        jHeavyBox.setOpaque(false);
        jHeavyBox.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/axe.png"))); // NOI18N
        jHeavyBox.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/bullet_ball_green.png"))); // NOI18N
        jPanel3.add(jHeavyBox);

        jRamBox.setText("Ramme");
        jRamBox.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/bullet_ball_red.png"))); // NOI18N
        jRamBox.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/bullet_ball_red.png"))); // NOI18N
        jRamBox.setDoubleBuffered(true);
        jRamBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/bullet_ball_grey.png"))); // NOI18N
        jRamBox.setOpaque(false);
        jRamBox.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/axe.png"))); // NOI18N
        jRamBox.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/bullet_ball_green.png"))); // NOI18N
        jPanel3.add(jRamBox);

        jPalaBox.setText("Paladin");
        jPalaBox.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/bullet_ball_red.png"))); // NOI18N
        jPalaBox.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/bullet_ball_red.png"))); // NOI18N
        jPalaBox.setDoubleBuffered(true);
        jPalaBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/bullet_ball_grey.png"))); // NOI18N
        jPalaBox.setOpaque(false);
        jPalaBox.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/axe.png"))); // NOI18N
        jPalaBox.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/bullet_ball_green.png"))); // NOI18N
        jPanel3.add(jPalaBox);

        jSnobBox.setText("AG");
        jSnobBox.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/bullet_ball_red.png"))); // NOI18N
        jSnobBox.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/bullet_ball_red.png"))); // NOI18N
        jSnobBox.setDoubleBuffered(true);
        jSnobBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/bullet_ball_grey.png"))); // NOI18N
        jSnobBox.setOpaque(false);
        jSnobBox.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/axe.png"))); // NOI18N
        jSnobBox.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ui/bullet_ball_green.png"))); // NOI18N
        jPanel3.add(jSnobBox);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jArriveField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(jSourceVillage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(jTargetVillage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jSourceVillage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTargetVillage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jArriveField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jLabel5.setText("Information");

        jScrollPane2.setBorder(null);

        jParserInfo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jParserInfo.setEditable(false);
        jParserInfo.setText("Es konnte\nBitte\nOder wen");
        jScrollPane2.setViewportView(jParserInfo);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );

        jCheckBox1.setText("Immer im Vordergrund");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fireComandDataChangedEvent(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_fireComandDataChangedEvent
        List<Village> villages = VillageParser.parse(jComandArea.getText());
        if (villages == null || villages.isEmpty() || villages.size() < 2) {
            return;
        }

        jSourceVillage.setText(villages.get(0).toString());
        jTargetVillage.setText(villages.get(1).toString());
        boolean fromSelection = false;
        try {
            String text = jComandArea.getText();
            String selection = jComandArea.getSelectedText();
            String arrive = null;

            if (selection == null) {
                String arriveLine = text.substring(text.indexOf("Ankunft:"));
                StringTokenizer tokenizer = new StringTokenizer(arriveLine, " \t");
                tokenizer.nextToken();
                String date = tokenizer.nextToken();
                String time = tokenizer.nextToken();
                arrive = date.trim() + " " + time.trim();
            } else {
                fromSelection = true;
                arrive = selection;
            }
            SimpleDateFormat f = new SimpleDateFormat("dd.MM.yy HH:mm:ss:SSS");
            Date d = f.parse(arrive);
            f = new SimpleDateFormat("dd.MM.yy 'um' HH:mm:ss.SSS");
            jArriveField.setText(f.format(d));
            jParserInfo.setText("Angriffsbefehl erfolgreich gelesen.");
        } catch (Exception e) {
            if (!fromSelection) {
                jParserInfo.setText("Es konnte keine Ankunftszeit gefunden werden.\nBitte markiere im oberen Textfeld die Ankunftszeit und -datum.");
                return;
            } else {
                jParserInfo.setText("Aus der Auswahl konnte keine Ankunftszeit bestimmt werden.\nBitte versuche, den Angriffsbefehl erneut zu kopieren oder wende dich an den DS Workbench Support.");
                return;
            }
        }



    }//GEN-LAST:event_fireComandDataChangedEvent

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new DSWorkbenchReTimerFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jArriveField;
    private javax.swing.JCheckBox jAxeBox;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JTextArea jComandArea;
    private javax.swing.JCheckBox jHeavyBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JCheckBox jLightBox;
    private javax.swing.JCheckBox jPalaBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextPane jParserInfo;
    private javax.swing.JCheckBox jRamBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox jSnobBox;
    private javax.swing.JTextField jSourceVillage;
    private javax.swing.JCheckBox jSpyBox;
    private javax.swing.JCheckBox jSwordBox;
    private javax.swing.JTextField jTargetVillage;
    // End of variables declaration//GEN-END:variables
}
