/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormConfigFrame.java
 *
 * Created on 06.01.2009, 10:38:27
 */
package de.tor.tribes.ui;

import de.tor.tribes.types.AbstractForm;
import de.tor.tribes.types.Circle;
import de.tor.tribes.types.Line;
import de.tor.tribes.types.Rectangle;
import de.tor.tribes.types.Text;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import net.java.dev.colorchooser.ColorChooser;

/**
 *
 * @author Charon
 */
public class FormConfigFrame extends javax.swing.JFrame {

    private AbstractForm mCurrentForm = null;
    private static FormConfigFrame SINGLETON = null;
    private ColorChooser mTextColorChooser = null;
    private ColorChooser mDrawColorChooser = null;
    private SamplePanel mSamplePanel = null;

    public static synchronized FormConfigFrame getSingleton() {
        if (SINGLETON == null) {
            SINGLETON = new FormConfigFrame();
        }
        return SINGLETON;
    }

    /** Creates new form FormConfigFrame */
    public FormConfigFrame() {
        initComponents();
        mTextColorChooser = new ColorChooser(Color.BLACK);
        mDrawColorChooser = new ColorChooser(Color.WHITE);
        ActionListener l = new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                updateValues();
            }
        };
        mDrawColorChooser.addActionListener(l);
        mTextColorChooser.addActionListener(l);
        jDrawColorPanel.add(mDrawColorChooser);
        jTextColorPanel.add(mTextColorChooser);
        mSamplePanel = new SamplePanel();
        jSamplePanel.add(mSamplePanel);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jFormName = new javax.swing.JTextField();
        jSamplePanel = new javax.swing.JPanel();
        jDrawName = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextTransparency = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jDrawTransparency = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDrawColorPanel = new javax.swing.JPanel();
        jTextColorPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jStrokeWidth = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jFillForm = new javax.swing.JCheckBox();
        jRoundBorders = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jTextHeight = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jDrawStartArrow = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jDrawEndArrow = new javax.swing.JCheckBox();

        setTitle("Form Einstellungen");
        setAlwaysOnTop(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(239, 235, 223));

        jLabel1.setText("Name/Text");

        jFormName.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                fireNameUpdateEvent(evt);
            }
        });

        jSamplePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Vorschau"));
        jSamplePanel.setOpaque(false);
        jSamplePanel.setLayout(new java.awt.BorderLayout());

        jDrawName.setText("Name zeichnen");
        jDrawName.setOpaque(false);
        jDrawName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fireDrawNameEvent(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Farben"));
        jPanel2.setOpaque(false);

        jLabel9.setText("Texttransparenz");

        jTextTransparency.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(0.9f), Float.valueOf(0.1f)));
        jTextTransparency.setMaximumSize(new java.awt.Dimension(80, 18));
        jTextTransparency.setMinimumSize(new java.awt.Dimension(80, 18));
        jTextTransparency.setPreferredSize(new java.awt.Dimension(80, 18));
        jTextTransparency.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fireTransparencyChangedEvent(evt);
            }
        });

        jLabel4.setText("Zeichentransparenz");

        jDrawTransparency.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(0.9f), Float.valueOf(0.1f)));
        jDrawTransparency.setMaximumSize(new java.awt.Dimension(80, 18));
        jDrawTransparency.setMinimumSize(new java.awt.Dimension(80, 18));
        jDrawTransparency.setPreferredSize(new java.awt.Dimension(80, 18));
        jDrawTransparency.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fireTransparencyChangedEvent(evt);
            }
        });

        jLabel5.setText("Textfarbe");

        jLabel2.setText("Zeichenfarbe");

        jDrawColorPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jDrawColorPanel.setMaximumSize(new java.awt.Dimension(80, 18));
        jDrawColorPanel.setMinimumSize(new java.awt.Dimension(80, 18));
        jDrawColorPanel.setOpaque(false);
        jDrawColorPanel.setPreferredSize(new java.awt.Dimension(80, 18));
        jDrawColorPanel.setLayout(new java.awt.BorderLayout());

        jTextColorPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextColorPanel.setMaximumSize(new java.awt.Dimension(80, 18));
        jTextColorPanel.setMinimumSize(new java.awt.Dimension(80, 18));
        jTextColorPanel.setOpaque(false);
        jTextColorPanel.setPreferredSize(new java.awt.Dimension(80, 18));
        jTextColorPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDrawColorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextColorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDrawTransparency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextTransparency, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextTransparency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDrawTransparency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextColorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDrawColorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Sonstiges"));
        jPanel3.setOpaque(false);

        jLabel3.setText("Strichbreite");

        jStrokeWidth.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(1.0f), Float.valueOf(0.1f), Float.valueOf(15.0f), Float.valueOf(0.1f)));
        jStrokeWidth.setMaximumSize(new java.awt.Dimension(80, 18));
        jStrokeWidth.setMinimumSize(new java.awt.Dimension(80, 18));
        jStrokeWidth.setPreferredSize(new java.awt.Dimension(80, 18));
        jStrokeWidth.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fireStrokeChangedEvent(evt);
            }
        });

        jLabel8.setText("Form ausfüllen");

        jFillForm.setOpaque(false);
        jFillForm.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fireFillChangedEvent(evt);
            }
        });

        jRoundBorders.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        jRoundBorders.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fireRoundBorderChangedEvent(evt);
            }
        });

        jLabel7.setText("Kantenrundung");

        jTextHeight.setModel(new javax.swing.SpinnerNumberModel(14, 10, 50, 1));
        jTextHeight.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fireTextHeightChangedEvent(evt);
            }
        });

        jLabel10.setText("Texthöhe");

        jLabel11.setText("Pfeil (Anfang)");

        jDrawStartArrow.setOpaque(false);
        jDrawStartArrow.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fireArrowsChanged(evt);
            }
        });

        jLabel12.setText("Pfeil (Ende)");

        jDrawEndArrow.setOpaque(false);
        jDrawEndArrow.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fireArrowsChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextHeight, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jStrokeWidth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRoundBorders, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(jFillForm, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)))
                    .addComponent(jDrawEndArrow, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(jDrawStartArrow, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jStrokeWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jFillForm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRoundBorders, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDrawStartArrow, 0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jDrawEndArrow, 0, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jSamplePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jFormName)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDrawName))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jFormName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDrawName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSamplePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setVisible(boolean v) {
        if (!v) {
            mCurrentForm = null;
        }
        super.setVisible(v);
    }

    public void setupAndShow(Class pType) {
        boolean isNoText = true;

        if (pType.equals(Line.class)) {
            mCurrentForm = new Line();
        } else if (pType.equals(Rectangle.class)) {
            mCurrentForm = new Rectangle();
        } else if (pType.equals(Circle.class)) {
            mCurrentForm = new Circle();
        } else if (pType.equals(Text.class)) {
            mCurrentForm = new Text();
            isNoText = false;
        }

        jLabel5.setEnabled(isNoText);
        jLabel2.setEnabled(isNoText);
        jLabel4.setEnabled(isNoText);
        jLabel11.setEnabled(isNoText);
        jLabel7.setEnabled(isNoText);
        jLabel8.setEnabled(isNoText);
        mDrawColorChooser.setEnabled(isNoText);
        jDrawTransparency.setEnabled(isNoText);
        jRoundBorders.setEnabled(isNoText);
        jDrawStartArrow.setEnabled(isNoText);
        jDrawEndArrow.setEnabled(isNoText);
        jFillForm.setEnabled(isNoText);
        jDrawName.setEnabled(isNoText);
        jDrawName.setSelected(!isNoText);
        setVisible(true);
        updateValues();
    }

    private void fireNameUpdateEvent(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_fireNameUpdateEvent
        updateValues();
}//GEN-LAST:event_fireNameUpdateEvent

    private void fireFillChangedEvent(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fireFillChangedEvent
        updateValues();
    }//GEN-LAST:event_fireFillChangedEvent

    private void fireStrokeChangedEvent(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fireStrokeChangedEvent
        updateValues();
    }//GEN-LAST:event_fireStrokeChangedEvent

    private void fireTransparencyChangedEvent(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fireTransparencyChangedEvent
        updateValues();
    }//GEN-LAST:event_fireTransparencyChangedEvent

    private void fireDrawNameEvent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fireDrawNameEvent
        if (!jDrawName.isEnabled()) {
            return;
        }
        updateValues();
    }//GEN-LAST:event_fireDrawNameEvent

    private void fireRoundBorderChangedEvent(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fireRoundBorderChangedEvent
        if (!jRoundBorders.isEnabled()) {
            return;
        }
        updateValues();
    }//GEN-LAST:event_fireRoundBorderChangedEvent

    private void fireTextHeightChangedEvent(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fireTextHeightChangedEvent
        updateValues();
    }//GEN-LAST:event_fireTextHeightChangedEvent

    private void fireArrowsChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fireArrowsChanged
        updateValues();
    }//GEN-LAST:event_fireArrowsChanged

    private void updateValues() {
        if (mCurrentForm != null) {
            mCurrentForm.setFormName(jFormName.getText());

            if (mCurrentForm instanceof Text) {
                ((Text) mCurrentForm).setTextColor(mTextColorChooser.getColor());
                ((Text) mCurrentForm).setTextSize((Integer) jTextHeight.getValue());
                ((Text) mCurrentForm).setTextAlpha(1.0f - (Float) jTextTransparency.getValue());
                mSamplePanel.setType(3);
            } else if (mCurrentForm instanceof Rectangle) {
                ((Rectangle) mCurrentForm).setStrokeWidth((Float) jStrokeWidth.getValue());
                ((Rectangle) mCurrentForm).setDrawColor(mDrawColorChooser.getColor());
                ((Rectangle) mCurrentForm).setTextColor(mTextColorChooser.getColor());
                ((Rectangle) mCurrentForm).setTextSize((Integer) jTextHeight.getValue());
                ((Rectangle) mCurrentForm).setDrawAlpha(1.0f - (Float) jDrawTransparency.getValue());
                ((Rectangle) mCurrentForm).setTextAlpha(1.0f - (Float) jTextTransparency.getValue());
                ((Rectangle) mCurrentForm).setDrawName(jDrawName.isSelected());
                ((Rectangle) mCurrentForm).setFilled(jFillForm.isSelected());
                ((Rectangle) mCurrentForm).setRounding((Integer) jRoundBorders.getValue());
                mSamplePanel.setType(1);
                mSamplePanel.setRoundBorders((Integer) jRoundBorders.getValue());
                mSamplePanel.setFill(jFillForm.isSelected());
                mSamplePanel.setDrawColor(mDrawColorChooser.getColor());
                mSamplePanel.setDrawTransparency(1.0f - (Float) jDrawTransparency.getValue());
                mSamplePanel.setStrokeWidth((Float) jStrokeWidth.getValue());
            } else if (mCurrentForm instanceof Circle) {
                ((Circle) mCurrentForm).setStrokeWidth((Float) jStrokeWidth.getValue());
                ((Circle) mCurrentForm).setDrawColor(mDrawColorChooser.getColor());
                ((Circle) mCurrentForm).setTextColor(mTextColorChooser.getColor());
                ((Circle) mCurrentForm).setTextSize((Integer) jTextHeight.getValue());
                ((Circle) mCurrentForm).setDrawAlpha(1.0f - (Float) jDrawTransparency.getValue());
                ((Circle) mCurrentForm).setTextAlpha(1.0f - (Float) jTextTransparency.getValue());
                ((Circle) mCurrentForm).setDrawName(jDrawName.isSelected());
                ((Circle) mCurrentForm).setFilled(jFillForm.isSelected());

                mSamplePanel.setType(2);
                mSamplePanel.setFill(jFillForm.isSelected());
                mSamplePanel.setDrawColor(mDrawColorChooser.getColor());
                mSamplePanel.setDrawTransparency(1.0f - (Float) jDrawTransparency.getValue());
                mSamplePanel.setStrokeWidth((Float) jStrokeWidth.getValue());
            } else if (mCurrentForm instanceof Line) {
                ((Line) mCurrentForm).setStrokeWidth((Float) jStrokeWidth.getValue());
                ((Line) mCurrentForm).setDrawColor(mDrawColorChooser.getColor());
                ((Line) mCurrentForm).setTextColor(mTextColorChooser.getColor());
                ((Line) mCurrentForm).setDrawAlpha(1.0f - (Float) jDrawTransparency.getValue());
                ((Line) mCurrentForm).setTextAlpha(1.0f - (Float) jTextTransparency.getValue());
                ((Line) mCurrentForm).setStartArrow(jDrawStartArrow.isSelected());
                ((Line) mCurrentForm).setEndArrow(jDrawEndArrow.isSelected());
                ((Line) mCurrentForm).setDrawName(jDrawName.isSelected());
                mSamplePanel.setType(0);
                mSamplePanel.drawStartArrow(jDrawStartArrow.isSelected());
                mSamplePanel.drawEndArrow(jDrawEndArrow.isSelected());
                mSamplePanel.setDrawColor(mDrawColorChooser.getColor());
                mSamplePanel.setDrawTransparency(1.0f - (Float) jDrawTransparency.getValue());
                mSamplePanel.setStrokeWidth((Float) jStrokeWidth.getValue());
            }

            mSamplePanel.setText(jFormName.getText());
            mSamplePanel.setDrawText(jDrawName.isSelected());
            mSamplePanel.setTextSize((Integer) jTextHeight.getValue());
            mSamplePanel.setTextColor(mTextColorChooser.getColor());
            mSamplePanel.setTextTransparency(1.0f - (Float) jTextTransparency.getValue());
            jSamplePanel.updateUI();
        }
    }

    public AbstractForm getCurrentForm() {
        return mCurrentForm;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FormConfigFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jDrawColorPanel;
    private javax.swing.JCheckBox jDrawEndArrow;
    private javax.swing.JCheckBox jDrawName;
    private javax.swing.JCheckBox jDrawStartArrow;
    private javax.swing.JSpinner jDrawTransparency;
    private javax.swing.JCheckBox jFillForm;
    private javax.swing.JTextField jFormName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSpinner jRoundBorders;
    private javax.swing.JPanel jSamplePanel;
    private javax.swing.JSpinner jStrokeWidth;
    private javax.swing.JPanel jTextColorPanel;
    private javax.swing.JSpinner jTextHeight;
    private javax.swing.JSpinner jTextTransparency;
    // End of variables declaration//GEN-END:variables
}
