/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LinkTagDialog.java
 *
 * Created on Jan 14, 2011, 10:11:11 PM
 */
package de.tor.tribes.ui;

import de.tor.tribes.types.LinkedTag;
import de.tor.tribes.types.Tag;
import de.tor.tribes.util.JOptionPaneHelper;
import de.tor.tribes.util.tag.TagManager;
import java.awt.event.ItemEvent;
import javax.swing.DefaultListModel;

/**
 *
 * @author Torridity
 */
public class LinkTagsDialog extends javax.swing.JDialog {

    private boolean bCreateLinkedTag = false;

    /** Creates new form LinkTagDialog */
    public LinkTagsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jLinkType.setSelectedIndex(0);
        fireLinkTypeChangedEvent(new ItemEvent(jLinkType, 0, null, ItemEvent.SELECTED));
    }

    public LinkedTag setupAndShow() {
        DefaultListModel leftModel = new DefaultListModel();
        DefaultListModel rightModel = new DefaultListModel();
        for (Tag t : TagManager.getSingleton().getTags()) {
            leftModel.addElement(t);
            rightModel.addElement(t);
        }
        jLeftTagList.setModel(leftModel);
        jRightTagList.setModel(rightModel);

        setVisible(true);

        if (bCreateLinkedTag) {
            int relationType = LinkedTag.AND_RELATION;
            String tagSymbol = "TAG1 und TAG2";
            if (jLinkType.getSelectedIndex() == 0) {
                relationType = LinkedTag.AND_RELATION;
                tagSymbol = "TAG1 und TAG2";
            } else if (jLinkType.getSelectedIndex() == 1) {
                relationType = LinkedTag.OR_RELATION;
                tagSymbol = "TAG1 oder TAG2";
            } else if (jLinkType.getSelectedIndex() == 2) {
                relationType = LinkedTag.XOR_RELATION;
                tagSymbol = "Entweder TAG1 oder TAG2";
            } else if (jLinkType.getSelectedIndex() == 3) {
                relationType = LinkedTag.NOT_RELATION;
                tagSymbol = "TAG1 und nicht TAG2";
            }
            Tag left = (Tag) jLeftTagList.getSelectedValue();
            Tag right = (Tag) jRightTagList.getSelectedValue();

            LinkedTag t = new LinkedTag(tagSymbol.replaceAll("TAG1", left.getName()).replaceAll("TAG2", right.getName()), true);
            t.setRelation(left.getName(), relationType, right.getName());
            t.updateVillageList();
            return t;
        }
        return null;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLeftTagList = new javax.swing.JList();
        jLinkType = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jRightTagList = new javax.swing.JList();
        jDoCreateButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tags verknüpfen");
        setAlwaysOnTop(true);
        setModal(true);

        jPanel1.setBackground(new java.awt.Color(239, 235, 223));

        jScrollPane1.setMinimumSize(new java.awt.Dimension(150, 130));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(150, 130));

        jLeftTagList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jLeftTagList);

        jLinkType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Und", "Oder", "Entweder/Oder", "Nicht" }));
        jLinkType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                fireLinkTypeChangedEvent(evt);
            }
        });

        jScrollPane2.setMinimumSize(new java.awt.Dimension(150, 130));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(150, 130));

        jRightTagList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jRightTagList);

        jDoCreateButton.setText("Erstellen");
        jDoCreateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fireAcceptEvent(evt);
            }
        });

        jButton2.setText("Abbrechen");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fireAcceptEvent(evt);
            }
        });

        jScrollPane3.setMaximumSize(new java.awt.Dimension(32767, 100));
        jScrollPane3.setMinimumSize(new java.awt.Dimension(24, 100));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(16, 100));

        jTextPane1.setBackground(new java.awt.Color(255, 255, 153));
        jTextPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Information"));
        jScrollPane3.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLinkType, 0, 92, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDoCreateButton)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLinkType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDoCreateButton)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fireLinkTypeChangedEvent(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_fireLinkTypeChangedEvent

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (jLinkType.getSelectedIndex() == 0) {
                jTextPane1.setText("Der resultierende Tag enthält alle Dörfer aus Gruppe 1 und alle Dörfer aus Gruppe 2.");
            } else if (jLinkType.getSelectedIndex() == 1) {
                jTextPane1.setText("Der resultierende Tag enthält alle Dörfer die sich in Gruppe 1, in Gruppe 2 oder in beiden Gruppen befinden.");
            } else if (jLinkType.getSelectedIndex() == 2) {
                jTextPane1.setText("Der resultierende Tag enthält alle Dörfer die sich nur in Gruppe 1 oder nur in Gruppe 2 befinden.");
            } else if (jLinkType.getSelectedIndex() == 3) {
                jTextPane1.setText("Der resultierende Tag enthält alle Dörfer die sich in Gruppe 1, aber nicht in Gruppe 2 befinden.");
            }
        }

    }//GEN-LAST:event_fireLinkTypeChangedEvent

    private void fireAcceptEvent(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fireAcceptEvent
        if (evt.getSource() == jDoCreateButton) {

            Object left = jLeftTagList.getSelectedValue();
            Object right = jRightTagList.getSelectedValue();

            if (left == null || right == null) {
                JOptionPaneHelper.showWarningBox(this, "Es muss auf der linken und auf der rechten Seite ein Tag ausgewählt sein.", "Warnung");
                return;
            }

            bCreateLinkedTag = true;
        }
        dispose();
    }//GEN-LAST:event_fireAcceptEvent

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                LinkTagsDialog dialog = new LinkTagsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jDoCreateButton;
    private javax.swing.JList jLeftTagList;
    private javax.swing.JComboBox jLinkType;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JList jRightTagList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
