/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TotDFrame.java
 *
 * Created on Apr 9, 2010, 2:32:40 PM
 */
package de.tor.tribes.ui;

import java.io.File;
import java.io.FileInputStream;
import java.util.Locale;
import java.util.Properties;
import javax.swing.JFrame;
import org.jdesktop.swingx.JXTipOfTheDay;
import org.jdesktop.swingx.plaf.TipOfTheDayUI;
import org.jdesktop.swingx.tips.DefaultTip;
import org.jdesktop.swingx.tips.TipLoader;
import org.jdesktop.swingx.tips.TipOfTheDayModel;

/**
 *
 * @author Torridity
 */
public class TotDFrame extends javax.swing.JFrame {

    private int iCurrentTip = 0;
    private static String TIP_DIR = "./totd/";
    private File[] tips = null;

    /** Creates new form TotDFrame */
    public TotDFrame() {
        initComponents();

        DefaultTip t = new DefaultTip();
        t.setTipName("Testing");
        t.setTip("Some tip");
        DefaultTip t2 = new DefaultTip();
        t2.setTipName("Testing1");
        t2.setTip("Some tip1");
        TipOfTheDayModel model = null;
        /* 
        System.out.println(model.getTipCount());
        jXTipOfTheDay1.setCurrentTip(0);*/
        try {
            //@TODO Load totd from server -> integrate into DSWB
            Properties p = new Properties();
            p.load(new FileInputStream(new File("tip.properties")));
            model = TipLoader.load(p);
            if (p.getProperty("enabled").equals("0")) {
                System.out.println("NOT");
            }
            jXTipOfTheDay1.setModel(model);
            jXTipOfTheDay1.setCurrentTip(1);
        } catch (Exception e) {
        }


        JXTipOfTheDay.ShowOnStartupChoice noshow = new JXTipOfTheDay.ShowOnStartupChoice() {

            public boolean isShowingOnStartup() {
                return true;
            }

            public void setShowingOnStartup(boolean showOnStartup) {
            }
        };
        ((TipOfTheDayUI) jXTipOfTheDay1.getUI()).createDialog(this, noshow).setVisible(true);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXTipOfTheDay1 = new org.jdesktop.swingx.JXTipOfTheDay();
        jXButton1 = new org.jdesktop.swingx.JXButton();

        setTitle("Tipp des Tages");

        jXButton1.setText("jXButton1");
        jXButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fireNext(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXTipOfTheDay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(309, Short.MAX_VALUE)
                .addComponent(jXButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jXTipOfTheDay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jXButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showTip() {
        /* File tip = tips[iCurrentTip];
        try {
        DataInputStream din = new DataInputStream(new FileInputStream(tip));
        byte[] data = new byte[(int) tip.length()];
        din.readFully(data);
        jEditorPane1.setText(new String(data));
        din.close();
        } catch (Exception e) {
        }*/
    }

    private void fireNext(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fireNext
        System.out.println(jXTipOfTheDay1.getCurrentTip());
        jXTipOfTheDay1.nextTip();
    }//GEN-LAST:event_fireNext

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Locale.setDefault(Locale.GERMAN);

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                TotDFrame f = new TotDFrame();
                f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                f.setVisible(true);
            }
        });


    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXButton jXButton1;
    private org.jdesktop.swingx.JXTipOfTheDay jXTipOfTheDay1;
    // End of variables declaration//GEN-END:variables
}
