/*
 * VillageInfoPanel.java
 *
 * Created on 5. September 2007, 23:09
 */

package de.tor.tribes.ui;

import de.tor.tribes.io.DataHolder;
import de.tor.tribes.types.Ally;
import de.tor.tribes.types.Tribe;
import de.tor.tribes.types.Village;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JFrame;

/**
 *
 * @author  Charon
 */
public class VillageInfoPanel extends javax.swing.JPanel {
    
    private DataHolder mHolder = null;
    private Village mVillage = null;

    /** Creates new form VillageInfoPanel */
    public VillageInfoPanel(DataHolder pHolder) {
        initComponents();
        mHolder = pHolder;
    }
    
    public void showVillage(int pX, int pY){
        mVillage = mHolder.getVillages()[pX][pY];
        if(mVillage == null) return;
        jVillageName.setText(mVillage.getName());
        String pos = Integer.toString(mVillage.getX()) + "|" + Integer.toString(mVillage.getY());
        jVillagePos.setText(pos);
        jVillagePoints.setText(Integer.toString(mVillage.getPoints()));
        
        Tribe t = mHolder.getTribes().get(mVillage.getTribe());
        if(t == null){
            jVillagePlayer.setText("Verlassen");
            jVillageTribe.setText("Keinen");
        }else{
            jVillagePlayer.setText(t.getName());
            Ally a = mHolder.getAllies().get(t.getAlly());
            if(a == null){
                jVillageTribe.setText("Keinen");
            }else{
                jVillageTribe.setText(a.getName());
            }
        }
    }
    
    private void setDefault(){
        jVillageName.setText("Unbekannt");
        jVillagePlayer.setText("Unbekannt");
        jVillagePos.setText("???|???");
        jVillagePoints.setText("Unbekannt");
        jVillageTribe.setText("Unbekannt");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jVillageName = new javax.swing.JLabel();
        jVillagePoints = new javax.swing.JLabel();
        jVillagePos = new javax.swing.JLabel();
        jVillagePlayer = new javax.swing.JLabel();
        jShowTribeInfo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jVillageTribe = new javax.swing.JLabel();
        jShowPlayerInfo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("Dorfname");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Punkte");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("Koordinaten");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel5.setText("Spieler");

        jVillageName.setText("Unbekannt");
        jVillageName.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jVillagePoints.setText("Unbekannt");
        jVillagePoints.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jVillagePos.setText("Unbekannt");
        jVillagePos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jVillagePlayer.setText("Unbekannt");
        jVillagePlayer.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jShowTribeInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jShowTribeInfo.setText("?");
        jShowTribeInfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jShowTribeInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jShowTribeInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fireShowAllyInfoEvent(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setText("Stamm");

        jVillageTribe.setText("Unbekannt");
        jVillageTribe.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jShowPlayerInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jShowPlayerInfo.setText("?");
        jShowPlayerInfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jShowPlayerInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jShowPlayerInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fireShowPlayerInfoEvent(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel2)
                            .add(jLabel5)
                            .add(jLabel3))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jVillagePos, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(jVillagePlayer, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jShowPlayerInfo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jVillagePoints, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .add(jVillageName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)))
                    .add(layout.createSequentialGroup()
                        .add(jLabel4)
                        .add(34, 34, 34)
                        .add(jVillageTribe, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jShowTribeInfo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(jShowPlayerInfo)
                    .add(jVillagePlayer, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jVillageName))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jVillagePoints))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jVillagePos))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(jShowTribeInfo)
                    .add(jVillageTribe))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void fireShowAllyInfoEvent(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fireShowAllyInfoEvent
        if(mVillage == null) return;
        Tribe t = mHolder.getTribes().get(mVillage.getTribe());
        if(t == null){
            jVillagePlayer.setText("Verlassen");
            jVillageTribe.setText("Keinen");
        }else{
            jVillagePlayer.setText(t.getName());
            Ally a = mHolder.getAllies().get(t.getAlly());
            if(a == null){
                jVillageTribe.setText("Keinen");
            }else{
                jVillageTribe.setText(a.getName());
            }
        }
}//GEN-LAST:event_fireShowAllyInfoEvent
    
private void fireShowPlayerInfoEvent(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fireShowPlayerInfoEvent
    
    if(mVillage == null) return;
    Tribe t = mHolder.getTribes().get(mVillage.getTribe());
    if(t == null){
        //no player
        return;
    }else{
        final JFrame f = new JFrame();
        f.setTitle("Spieler " + t.getName());
        PlayerInfoPanel pinfo = new PlayerInfoPanel(mHolder);
        pinfo.showPlayer(t.getId());
        f.add(pinfo);
        f.setLocationRelativeTo(this);
        f.setLocation(getMousePosition());
        f.pack();
        f.setVisible(true);
    }
}//GEN-LAST:event_fireShowPlayerInfoEvent


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jShowPlayerInfo;
    private javax.swing.JLabel jShowTribeInfo;
    private javax.swing.JLabel jVillageName;
    private javax.swing.JLabel jVillagePlayer;
    private javax.swing.JLabel jVillagePoints;
    private javax.swing.JLabel jVillagePos;
    private javax.swing.JLabel jVillageTribe;
    // End of variables declaration//GEN-END:variables
    
}
